// <auto-generated />
using System;
using Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260121154206_UserUpdatedAtNullable")]
    partial class UserUpdatedAtNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Challenge", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsArchive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_challenge");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_challenge_author_id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_challenge_id");

                    b.ToTable("challenge", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsArchive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archive");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_user_id");

                    b.HasIndex("TelegramId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_telegram_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_user_username");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserChallengeBind", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ChallengeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("challenge_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_challenge_bind");

                    b.HasIndex("ChallengeId")
                        .HasDatabaseName("ix_user_challenge_bind_challenge_id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_user_challenge_bind_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_user_challenge_bind_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_challenge_bind_user_id");

                    b.ToTable("user_challenge_bind", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserChallengeCheckIn", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CheckInDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("UserChallengeBindId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_challenge_bind_id");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_challenge_check_in");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_user_challenge_check_in_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_user_challenge_check_in_status");

                    b.HasIndex("UserChallengeBindId")
                        .HasDatabaseName("ix_user_challenge_check_in_user_challenge_bind_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_challenge_check_in_user_id");

                    b.ToTable("user_challenge_check_in", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Challenge", b =>
                {
                    b.HasOne("Domain.Entities.User", "Author")
                        .WithMany("CreatedChallenges")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_challenge_user_author_id");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Domain.Entities.UserChallengeBind", b =>
                {
                    b.HasOne("Domain.Entities.Challenge", "Challenge")
                        .WithMany("Participants")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_challenge_bind_challenge_challenge_id");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("ParticipatingChallenges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_challenge_bind_user_user_id");

                    b.Navigation("Challenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.UserChallengeCheckIn", b =>
                {
                    b.HasOne("Domain.Entities.UserChallengeBind", "UserChallengeBind")
                        .WithMany("CheckIns")
                        .HasForeignKey("UserChallengeBindId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_challenge_check_in_user_challenge_bind_user_challenge_");

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany("ChallengeCheckIns")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_user_challenge_check_in_user_user_id");

                    b.Navigation("UserChallengeBind");
                });

            modelBuilder.Entity("Domain.Entities.Challenge", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("ChallengeCheckIns");

                    b.Navigation("CreatedChallenges");

                    b.Navigation("ParticipatingChallenges");
                });

            modelBuilder.Entity("Domain.Entities.UserChallengeBind", b =>
                {
                    b.Navigation("CheckIns");
                });
#pragma warning restore 612, 618
        }
    }
}
